### ISSUE TITLE
linter to be invoked in connection with wiki2 direct edits

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#440]
direct https://github.com/rusefi/rusefi/wiki/ edits are an amazing tool for myself @rusefillc 

Linter is an amazing tool helping wiki quality

We need to bring these two closer together. Can we have lint invoked during syncs or periodically or else?

**Comment by rusefillc** [comment]
Actually weird, I clearly remember sync failing when we had errors in miata file https://github.com/rusefi/rusefi_documentation/commit/9687323aaa2f0c613fe6875c2d59ac2bd1cd4159

So it look like lint is invoked at least for some sync, could it be invoked only for one direction and not for both?

**Comment by rusefillc** [comment]
@chuckwagoncomputing please help :)

**Comment by chuckwagoncomputing** [comment]
Re: sync failing because of miata file:
There are two different checks:
1. MKDocs' built-in checks
2. The Lint job

The failed sync was because of 1.
2 doesn't happen with the wiki sync job.


Re: Adding lint check to wiki sync
What would be the expected behavior of a failed lint?
1. Failing wiki sync is considered harmful because it can cause repository states that are no longer auto-mergeable.
2. Having the linter run after the sync would work, and you would receive an email notifying you of the failure.
However, the repository state would be "broken", and if someone else tried to make a PR before you fixed what you've broken, the linter job on the PR would fail. This is kind of how things already are, so it would be an improvement for you to get an email telling you that you did something wrong.

**Comment by rusefillc** [comment]
> Having the linter run after the sync would work, and you would receive an email notifying

This would be best balance of drama and safety!

**Comment by rusefillc** [comment]
> This is kind of how things already are, so it would be an improvement for you to get an email telling you that you did something wrong.

At the moment I do not get email thus do not notice breakage
